# the type of the container (normal trace or fixed-random trace or real trace)
mode: 'normal'

# scan mode (run iteratively to cover all possible parameters (pre defined))
scan: true

# the total number of key guesses used in the cpa attack
# the index of the correct key guess
no_of_key_guesses: 256
idx_of_correct_key_guess: 0

# engine name (trivial)
engine_name: 'cmi'

# attack range
# attack specific time range of the generated traces (python generator)
attack_range: range(0, 4)

# number of shuffles
num_shuffles: 25

# batch size
batch_size: 10000

# plotting params
figure_params : {'title': ['cmi+mi', 'cmi+pv'] , 'x_label': ['time', 'time'], 'y_label': ['mi', 'pv']}